### ISSUE TITLE
Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by black-snow** [jprichardson/electron-mocha#104]
Platform: Windows 10 Creators Update
Version: 3.4.0 (latest)
electron-version: 1.6.10 (latest)
node-version: v8.0.0
Invocation: `electron-mocha app/specs.js.autogenerated --renderer --require source-map-support/register`

Error:
```
const tmpdir = fs.mkdtempSync(join(app.getPath('temp'), 'electron-mocha-'))
                                      ^
 
TypeError: Cannot read property 'getPath' of undefined
    at Object.<anonymous> (E:\xyz\node_modules\electron-mocha\index.js:17:39)
    at Object.<anonymous> (E:\xyz\node_modules\electron-mocha\index.js:100:3)
    at Module._compile (module.js:571:32)
```

`console.log(app)` in index.js before line 17 yields `undefined`
`console.log(require('electron')` yields the path to the electron exe

**Comment by black-snow** [comment]
Seems to be an issue with Power Shell. It works using git bash except the following error:

```
UncaughtException:
Error: EPERM: operation not permitted, unlink
'C:\Users\xxx\AppData\Local\Temp\electron-mocha-xyz\GPUCache\data_0
...
at fixWinEPERMSync
```

**Comment by inukshuk** [comment]
About your first problem: if `require('electron') yields the path to electron this means that you're likely not using Electron's `require` and loading the `electron` module instead of the Electron API. This shouldn't happen in electron-mocha unless you're using some kind of pre-processor to bundle your tests?

About the second issue: normally, if the temp folder can't be removed (especially on Windows) it means that some of your tests opened resources and did not release them again. In this case it's likely a window -- if any of your tests open windows you need to make sure to close them again otherwise the temp folder can't be cleared.

**Comment by black-snow** [comment]
Thanks for your detailed reply.
