### ISSUE TITLE
Support html reporter (and custom index.html?)

### ISSUE THREAD

**Issue by HeilTec** [jprichardson/electron-mocha#117]
##### When running a test, a message is inserted into the document: "missing #mocha div"

Easy Fix: Added 
```html 
  <div id="mocha"></div>
```
to `./renderer/index.html`

##### Test results appears with no styling

Fix: Added 
```html 
  <link rel="stylesheet" href="mocha.css">
```
to `./renderer/index.html` and then it looks nice.

### Now the main issue:

When clicking on the links containing 
   `{project}/node_modules/electron-mocha/renderer/index.html?grep={testLabel}`
two errors occurs:

1. In the terminal:
    Cannot read property 'forEach' of undefined
    TypeError: Cannot read property 'forEach' of undefined
        at Object.<anonymous> ({project}/node_modules/electron-mocha/renderer/run.js:14:15)

2. A JavaScript error occurred in the main process (popup)
    Uncaught Exception:
    Error: Object has been destroyed
        at EventEmitter.ipc.on ({project}/node_modules/electron-mocha/index.js:83:14)

Options given as location.hash when the window loads first time are lost when clicking the links (1) 
??? (2)

Versions

    $ electron -v
    v1.6.11
    $ ./node_modules/.bin/electron-mocha --version
    5.0.0
    $ node -v
    v6.11.5

**Comment by HeilTec** [comment]
I suspect I'm doing something completely wrong.
I should have my own 'index.html' and not patch in node_modules.

**Comment by inukshuk** [comment]
Yes, the `--interactive` flag was added primarily to show the window in order to give you access to the devtools and the debugger; electron-mocha assumes you're using mocha like you would use it in Node.js not in the browser (i.e., not the HTML reporter but rather the doc reporter).

That said, it's an interesting idea to support the HTML reporter for the combination of `--renderer --interactive` (using HTML reporter could automatically force those flags) and/or allowing you to link to your own `index.html` (a feature which was already requested a few times).

**Comment by HeilTec** [comment]
I think an electron reporter might be what will do the trick.
I patched together the html reporter from the builtin reporters in mocha with the required pieces to make a preliminary html_electron reporter.

My working model is now based on patching the index.html in electron-mocha and then using this [html_electron.js](https://gist.github.com/HeilTec/fa51fbf36716259fedf07abb990cd646)

I still need to implement passing on the `?grep=<text>` search argument to the runner.

**Comment by marc2332** [comment]
Hello 👋🏻 

You can now use custom index.html via the `--url`  or `--index` argument.
