### ISSUE TITLE
timeout not working

### ISSUE THREAD

**Issue by purefan** [jprichardson/electron-mocha#121]
Hello!

When running tests against an electron app I need to wait for the dom to be drawn, in each test I can write something like 
```
it('checks something', function() {
    setTimeout(actual_test, 1000)
    function actual_test() { ... }
})
```
But that's _dirty_. 

I've tried 
```
it('checks something', function() {
    this.timeout(1000)
    assert(...)
})
```

And while it doesn't fail, it also doesn't seem to wait for anything. Am I doing something wrong?

**Comment by inukshuk** [comment]
This isn't really specific to `electron-mocha`, but `mocha` in general: for async tests you need to use mocha's `done` callback or return a promise (or use special assertions such as those provided by 'chai as promised') otherwise your tests won't wait for the async assertion (note that it is often easier to experiment with these sort of tests with failing assertions, because it's hard to tell otherwise whether or not your assertion was actually called).

In your second example, you're only changing the test's timeout (the time it will wait for an async assertion) -- it won't wait for anything.
