### ISSUE TITLE
Invalid reporter "mocha-teamcity-reporter"

### ISSUE THREAD

**Issue by jhdevuk** [jprichardson/electron-mocha#127]
Hi,

I've got our unit tests running in Electron now using this package, however we require reporting through our CI build server, TeamCity.

Mocha has a third party reporting package, but for some reason this doesn't work when using `electron-mocha`.

```
Error: invalid reporter "mocha-teamcity-reporter"
```

As this is a drop in replacement for `mocha` is there something I've missed in the npm script:
`"test-teamcity": "electron-mocha -R mocha-teamcity-reporter --require ./Content/tests/client/compile.js --renderer ./Content/tests/client/src/**/*.spec.ts",`

Thanks for any help, much appreciated.

@inukshuk @jprichardson

**Comment by inukshuk** [comment]
I think this is an issue with the reporter. Mocha / Electron-Mocha tries to load the reporter automatically, but requiring it fails in the Renderer process; since the reporter loads just fine in Main and I've seen no issues requiring other modules in Renderer I'm assuming this is a problem with the reporter package (my guess is that they're trying to detect the browser/node environment and something about the Electron Renderer environment causes it go off script).

Here's a quick test:

     $ npm init
     $ npm i electron-mocha mocha-teamcity-reporter --save-dev

Create `spec/index_test.js`:

    describe('a test', () => {
      it('works', () => {
        require('mocha-teamcity-reporter')
      })
    })

Observe:

    $ $(npm bin)/electron-mocha spec
    #-> runs just fine
    $ $(npm bin)/electron-mocha spec --renderer
    #-> fails with: Error: Cannot find module './base'

I'd check with the authors of the reporter if they can help or have an idea why the module fails to load in an Electron Renderer process.
