### ISSUE TITLE
Error: No test files found, using latest versions

### ISSUE THREAD

**Issue by nlfiedler** [jprichardson/electron-mocha#149]
Using electron-mocha 8.1.1 and mocha 6.2.0 I get the error above. Was working a few weeks ago, and I hadn't touched the project recently. Then did `npm i` today and probably got newer versions of dependencies; as a result the tests stopped working.

Tests are in `test` and named with `.js` suffix, no TypeScript or anything complicated. Was running the tests like so: `NODE_ENV=test electron-mocha --color` -- got around the problem for now by adding `'test/**/*.js'` on the end. Seems unexpected that I should have to do that. Am I wrong? Thanks.

**Comment by inukshuk** [comment]
Thanks, you're right, we dropped the default spec path accidently -- this will be fixed in the upcoming patch release.

The default path used by mocha is just `'test'`, so we will use that as well (this will not find tests in sub-directories so you might still have to set path in your example above).
