### ISSUE TITLE
Renderer process code coverage when running app

### ISSUE THREAD

**Issue by lutzroeder** [jprichardson/electron-mocha#176]
### Problem Description

Record code coverage data for the renderer process when running the app manually. 

`nyc --reporter=lcov npx electron .` records coverage data for the main process but not for the renderer process.

### Additional Information

electron/electron#26843

**Comment by inukshuk** [comment]
You need to either instrument your code beforehand, or instrument the code as you load it into the renderer. Then write the coverage state out before exiting. You can use `nyc` to combine the coverage reports of both processes later on.

For example see here:
* Instrument code before loading (using a babel plugin in this case): https://github.com/tropy/tropy/blob/master/test/support/babel.js#L15
* Write out renderer stats after tests finsih: https://github.com/tropy/tropy/blob/master/test/support/coverage.js
* Combine results: https://github.com/tropy/tropy/blob/master/package.json#L41

**Comment by lutzroeder** [comment]
@inukshuk to simplify with `.js` files only, these steps should work?

1. `nyc instrument ./source ./source_nyc`
2. rename `main` in `package.json` to `source_nyc/app.js`
3. `nyc --reporter=lcov nyc --reporter=lcov npx electron .`

**Comment by inukshuk** [comment]
I'm assuming step 2 saves the instrumented code in `source_nyc`? Then it should work if you write out the coverage stats at the end of your renderer tests: `nyc` in step 4 will only collect the stats from the main process, that's why you need to do this yourself. `nyc` is still useful to combine the results of both processes into a single report at the end.
