### ISSUE TITLE
Upgrade to a more current version of mocha

### ISSUE THREAD

**Issue by JJ** [jprichardson/electron-mocha#189]
Among other things, former version includes ansi-regex 3.0.0, which has a [vulnerability](https://github.com/advisories/GHSA-93q8-gq69-wqmw)

**Comment by inukshuk** [comment]
Thanks for the PR but unfortunately we can't just upgrade like that. Mocha version 9 has a breaking change, loading dependencies with `import` first. This is no problem in the Electron main process but causes serious headaches in the renderer, because there Chromium's ESM loader will be used instead of the Node.js one which means you wouldn't be able to load any Node.js modules from your tests.

We'll upgrade eventually but we need to find a good solution for the ESM loader issue first.

**Comment by JJ** [comment]
Fair enough. Thanks for the clarification.

**Comment by inukshuk** [comment]
Closed by https://github.com/jprichardson/electron-mocha/commit/6f027d898d351cc12baf8492205c1bf2a035d875
