### ISSUE TITLE
Examples of tests written to leverage electron-mocha

### ISSUE THREAD

**Issue by madarche** [jprichardson/electron-mocha#35]
Hello

It would be great if this project had an `examples` folder containing 2 tests (one for the main process, one for a renderer process) for testing a fictional Electron demo app.

At the moment I'm a bit stuck in my tests, not knowing how to go further than just testing pure CommonJS modules, that is all what is not specific to Electron. Some things I would like to do:

* Test a renderer process HTML view
* Test a renderer process JavaScript
* Show a menu and activate a menu item

Thanks a lot

**Comment by jprichardson** [comment]
See: https://github.com/jprichardson/electron-mocha/tree/master/test

**Comment by madarche** [comment]
I have already read those https://github.com/jprichardson/electron-mocha/tree/master/test files, but they don't answer to the questions:
* How to test a renderer process HTML view (what HTML elements there are in the DOM document of the view)
* How to test a renderer process JavaScript
* How to show a menu and activate a menu item

Wouldn't it better to leave this issue open until there are more meaningful examples?

I'm willing to provide (through a PR) the very simple Electron demo app and the 2 tests (for main and renderer) mentioned at the top if someone then provide me with guidance to craft meaningful tests. Are you interested?

**Comment by tscanlin** [comment]
+1 to more examples, they would be really helpful. But great work building this!

I started reading through the source code of this project and it seems like its more made to run mocha tests for electron apps or node / react apps so that they can use the DOM and native browser methods rather than working with some browser tests that are run from a URL.

For this reason I created https://github.com/tscanlin/mocha-electron, maybe you will find it useful for your purposes @madarche 

Let me know if I'm misunderstanding and there is a way to pass a url to electron-mocha for testing. I'm also open to merging these projects, but right now it seems like these are targeted at pretty different use cases.

**Comment by madarche** [comment]
Thanks @jprichardson for reopening the issue. Thanks @tscanlin for publishing mocha-electron. I'm going to test mocha-electron too and will report here asap!

**Comment by madarche** [comment]
@tscanlin: I have checked [mocha-electron](https://github.com/tscanlin/mocha-electron). I will use it for testing web sites/apps, so the ability to pass an URL to mocha-electron is interesting in this case. But when I need to test an electron app, I need a tool like electron-mocha

**Comment by tscanlin** [comment]
Thanks for the update @madarche, and I'm glad you find it useful for websites and web apps. It wasn't intended to be used for electron apps so I would keep using electron-mocha for that as you said. It sounds like both of these tools have their place.

**Comment by rgbkrk** [comment]
I just started using this today in https://github.com/nteract/composition, my tests are pretty identical to what I used to do with JSDom except now I don't have to run a helper script to initialize `document` and `window`.

Before:

```
    "test": "mocha --compilers js:babel-core/register --require ./test/test_helper.js 'test/**/*.@(js|jsx)'",
```

After:

```json
    "test": "electron-mocha --renderer --compilers js:babel-core/register 'test/**/*.@(js|jsx)'",
```

Everything else is the same, I can work on the DOM freely. Test results end up in the console where I want them (since I also run this headless on Travis).

**Comment by madarche** [comment]
@rgbkrk I'm sorry the repository you're mentioning doesn't contain the answers I'm looking for. Please read my PR if you are interested in what I would like to be able to do.

**Comment by rgbkrk** [comment]
That's ok! Your example with tests makes pretty clear sense.

**Comment by madarche** [comment]
As explained in details in #38 by @inukshuk, electron-mocha is just to run Mocha tests in Electron, not to test Electron apps.
