### ISSUE TITLE
Specify alternative electron version to run tests with

### ISSUE THREAD

**Issue by trodi** [jprichardson/electron-mocha#73]
**Issue**
I need to have electron-mocha use a different version of electron than what is specified in my package.json.

**Use case**
The current version of electron that is used in my project currently has issues when running via electron mocha (others have hit issues with various versions of electron e.g., Issue #66 ). Since it isn't always an option to immediately update the version of electron being used (this can require native addon changes), it would be handy to allow running the tests with a different version than locally installed.

Issue #4 PR #55 added support for electron-mocha to use the locally installed version which is great. The change first does a check on `which electron`, which will return the globally installed version if in a terminal, but the local version if running via an npm script. Thus if my `npm test` calls electron-mocha, it will _always_ load the local copy and ignore $ELECTRON_PATH.

**Solution**
To solve immediately for myself, I've edited the which check to first look at the ELECTRON_PATH before PATH, then fallback to the require for the local install. 
`electron = process.env.ELECTRON_PATH || electron`

I'm note sure if this is the best global solution, though I'll create a PR if this is acceptable. Alternatively, an additional param could be optionally passed when calling electron-mocha to specifies a path to electron.

I'm curious if there is a preferred method of dealing with this use case. Thanks.

**Comment by inukshuk** [comment]
I think if you have a version of Electron specified in your package.json electron-mocha should use that version. I don't really understand why you would want to run your tests with a different version of Electron than your app uses -- isn't the point to test that the code works in your app?

If your version of electron has issues with electron-mocha you could always install an older version of electron-mocha (which works with your Electron version) -- #66 is not a good example, because Electron 1.2.0 is just seriously broken and I see no reason why you would not at least want to upgrade to another 1.2.x version (which should not require native module changes, in my experience, as the Node version will remain the same).

Having said that, I don't know what the rationale for the current order is, but specifying an Electron version in package.json and then using another one seems counter intuitive to me.

**Comment by trodi** [comment]
The use case I present is abnormal. By default, you are correct, you should choose the same version as in the package.json file. Though being able to run tests in an electron environment (even if it isn't the exact same as production), still has value similar to using PhantomJS to gain access to the general environment.

#66 was just an example I found listed in this project that had caused issues; it may not have been the perfect example. I'm using Electron v0.37.8 and there are many v8 upgrades between that and the current release. Using an older version of `electron` caused issues with `electron-mocha`. Using an older version of `electron-mocha` caused issues for my teammates running windows + cygwin (I didn't exhaustively review all version combinations).

My case was to provide an override if necessary, **which you may decide is not in line with the project, which is fair**. It seems that most/all projects should specify a local version in the package.json, making the `PATH` no-ops. So the `PATH` variables made me think of overrides. Though, as noted originally, maybe if an override was intended/supported, maybe it would have been an explicit flag.

Either way, thanks for providing a useful project 😄

**Comment by inukshuk** [comment]
OK, I still don't quite see the usefulness, but I don't think it's hurts to give precedence to the env variable to make it easier to override. Landed in 3.0.1.

Side note: the current release of electron-mocha will not work with a lot of Electron 0.x code -- so any of your code which uses the old Electron API will be hard to test.
