### ISSUE TITLE
with `--interactive` option page reload doesn't rerun tests

### ISSUE THREAD

**Issue by artemave** [jprichardson/electron-mocha#96]
testSpec.js:
```
describe('--interactive not working', () => {
  it('works initially but not when page is reloaded', () => {
  });
});
```
command:
```
electron-mocha --interactive test/testSpec.js
```

Test runs for the first time (I can see the output in dev tools console) but when I refresh the window it doesn't rerun (no output).

versions:
```
    "electron-mocha": "3.2.1",
    "electron-prebuilt": "1.4.12",
```

node 7.2.0

**Comment by artemave** [comment]
Fixed it. Turns out tests were only running on initial page load: https://github.com/artemave/electron-mocha/commit/c62358fde37c9dc87a5081038720cad37f6181c4

Didn't look at the tests yet. Let me know if there need to be some and then I'll submit a pr.

**Comment by inukshuk** [comment]
You're right that's odd. @as-cii did we miss something when we pulled #91?

Anyway, @artemave this looks good, I'd be happy to merge a PR. I wonder if we could eliminate the `firstRun` variable though? The `ready-to-show` event should fire just once initially, not on subsequent reloads I believe (we can use `.once` instead of `.on` to express this expectation more clearly, too) so we might not need it... (but I can look at that later). Also, let's use the `mocha-` prefix for the event name, i.e., `mocha-ready-to-start` or something like that?)

**Comment by as-cii** [comment]
Thanks @inukshuk and @artemave, sorry for the oversight! 🙇
